# Generated by Django 5.2.1 on 2025-05-24 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mask',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.mask'),
            preserve_default=False,
        ),
    ]
