# Generated by Django 5.2.1 on 2025-05-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transaction_mask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyopeninghour',
            name='day_of_week',
            field=models.CharField(max_length=4),
        ),
    ]
